import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "học lập trình để đi làm ",
  description: "Generated by create next app",
  keywords: "f8, html-css",
  openGraph: {
    title: "học lập trình để đi làm ",
    images: ["https://fullstack.edu.vn/images/img.jpg"],
  },
  icons: {
    icon: "https://fullstack.edu.vn/assets/f8-icon-lV2rGpF0.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
