import Nav from "./Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemeProvider from "./ThemeProvider";
import ProvidersNextAuth from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Nav />
          <ProvidersNextAuth>{children}</ProvidersNextAuth>
        </ThemeProvider>
      </body>
    </html>
  );
}
